version: '3.3'

services:
  related-info:
    image: ganzfriend/related-info:latest
    depends_on:
      - database
    ports:
      - 3000:3000
  host-info:
    image: ganzfriend/host-info:latest
    depends_on:
      - database
    ports:
      - 3001:3001
  reviews:
    image: ganzfriend/reviews:latest
    depends_on:
      - database
    ports:
      - 3003:3003
  proxy:
    image: ganzfriend/fec-proxy:latest
    depends_on:
      - database
    ports:
      - 3005:3005
  database:
    image: mongo:latest
    container_name: database
    ports:
      - 27017:27017
    volumes:
      - /data/db